### ISSUE TITLE
Implement project landing pages

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#10]
The new structure on edgeryders.eu will require one landing page for each current project that we run (say: OpenCare, MENA Youth Platform, …). They would fulfill the same role as the current challenge chain pages ([example](https://edgeryders.eu/it/node/7747)), but not require all the UI elements shown there.

**What should be shown there is:**

- A description what the project is about, as formatted text, allowing to include images etc..
- A UI element to contribute your own content (ideally customizable).
- A list of the areas ("challenges") inside this project where people can contribute their content.
- A list of content, or most recent content only, that has already been contributed to this project.

**Implementation proposal:** In all probability, we will decide to implement our projects as Discourse categories, and the projects' challenges as sub-categories below that. This way, the Discourse category page already provides the list of challenges (as list of sub-categories), the list of existing content (as list of topics in the category). Discourse has a way to create a description for the category, using an auto-created pinned topic in there. There is however no way to show the content of that topic on the page of the category, so this would be the part where we need some custom development. With this proposal, we stick to the current Discourse way of doing category descriptions (as much as possible), so it has the benefit that formatting options, access rights etc. are all already managed by Discourse. An alternative implementation proposal would be to use an own implementation of static pages for this, but it does not have these advantages of letting Discourse care for most of the details.

**Comment by tanius** [comment]
**Newest implementation proposal:** After implementing #23 ("sub-category previews"), we have two of the four desired elements available on a project's category page:

- A list of the areas ("challenges") inside this project where people can contribute their content.
- A list of content, or most recent content only, that has already been contributed to this project.

It is not suitable to also add a length description right on that page, so for that we should have (and already have) a static page per project, introducing a user to the project, and being linked from our custom navbar. This gives us the third element:

- A description what the project is about, as formatted text, allowing to include images etc..

What's still missing is:

- A UI element to contribute your own content (ideally customizable).

This should be both on the project's static page, and the project category page. (There is "+ New Topic" on the category page, but that's not enough, and not customizable.) The simplest way to add it would be a direct link, or otherwise JavaScript action, to call up the Discourse editor with the target category already pre-selected.

**Comment by noemisalantiu** [comment]
On it! I am working on those 3 + Arrivals (added the photo + updated copy).

I noticed while browsing through the key static pages accessible from the menus that the topics listed on [this page](https://discourse.edgeryders.eu/t/all-our-projects/40) are currently outdated (not sure if they are randomized..) Can I ask that they are rendered the same as those listed in Arrivals/Agora? https://discourse.edgeryders.eu/t/all-our-projects/40. They are more likely to interest users.

**Comment by tanius** [comment]
@noemisalantiu You're referring to the "Suggested Topics" list at the bottom of [that page](https://discourse.edgeryders.eu/t/40), right? In that case, we'll just remove that list completely for now. (I added the request to #32, will be done before launch.) If you want a list of forum topics on static pages for later, request that in a new issue please. It can't be implemented with the current system, as we can only either show "Suggested Topics" from the same category, or randomly from any category.

**Comment by tanius** [comment]
First iteration of these pages, and content in them, is about finished now :slightly_smiling_face:
