### ISSUE TITLE
Include Redis in the process monitoring

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#103]
On 2017-09-29 in the morning we had the (first) case that the Redis server process had died, and our Discourse platform was no longer accessible. Starting Redis again solved that.

So it seems Redis is not yet included in the `monit` based process monitoring on the server, with automatic restarts. Seems a good idea to add it there :)

**Comment by damingo** [comment]
Now monitored by monit. Config file in /etc/monit/conf.d/redis.conf
