### ISSUE TITLE
Allow creating Open Ethnographer tags on the fly

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/discourse#105]
Error message: "There was a problem connecting with the annotation store"

Never seen that one before. Open Ethnographer accepted the annotation, but we got the message above. We think the annotations were not saved to the database.

**Comment by tanius** [comment]
To work on this, we'll need info about how to reproduce this, and if it was reproducible when it happened.

(Removing from the milestone until then.)

**Comment by albertocottica** [comment]
Still happening. To reproduce, just make an annotation. It is not consistent, though. So... I guess make 10 or 20 annotations.

**Comment by albertocottica** [comment]
Ok, I think I got it. If you create a new annotation that re-uses an existing code, it goes through. If you create a new annotation that uses a _new_ code,  you get the error. @damingo @tanius

**Comment by tanius** [comment]
>  If you create a new annotation that uses a new code, you get the error.

True. I got the error myself now. This feature was simply not implemented yet. I have adapted the issue description since then.
