### ISSUE TITLE
Can the DB record the author of a tag?

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/discourse#11]
This will allow realise the Massive Open Online Ethnography vision ("pull in all the annotations/codes by researcher XYZ"). 

This has been a pain point in Drupal. Under our setting, there is no way for Amelia to parse her codes from Inga's.

**Comment by tanius** [comment]
Future Open Ethnographer's tags / codes will most likely not be stored as Discourse tags, but in a new, own table (or even a new database, decreasing the coupling further). Then, of course we can record authors of codes alongside.

While we're at this: word-based ethnographic codings cannot be imported into Discourse right now. How to get Open Ethnographer up and running again for Discourse is yet another discussion. I'd look into the direction of the original Annotator (on which Open Ethnographer is based), which can easily be added to any website as a browser plugin.
