### ISSUE TITLE
Position the cursor in the annotator tag field after clicking on the pencil icon to add an annotation

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/discourse#110]
Should be self explanatory. Click on the pencil icon, you should be able to start typing immediately.

**Comment by tanius** [comment]
Confirmed. Makes sense.

Refers to our Open Ethnographer implementation. Namely, when selecting text and clicking the pencil icon to add a new annotation, the little Annotator.JS overlay window will appear. Then, the text insertion mark should already be active and blinking in the field titled "Add some tags here …".
