### ISSUE TITLE
Expose API for annotator tags

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#111]
As [discussed](https://github.com/edgeryders/discourse/issues/97#issuecomment-344231995) after finishing the original implementation of the Open Ethnographer API, we need one more API endpoint.

It should provide the information about annotator tags ("ethnographic codes") as provided on  https://edgeryders.eu/administration/annotator/tags, but in JSON format. The proposed URL for that API endpoint is https://edgeryders.eu/administration/annotator/tags.json.

Should be just a list of all annotator tags with associated information. If filter options ("annotator tags by author" etc.) are required: @jason-vallet please tell here. Also please advise on required completion date of this feature.

**Comment by albertocottica** [comment]
Jumping in to ask how you (@tanius) think this is best done. We could: 

* implement an endpoint as a list of codes (please, codes, not tags, to avoid confusion with Discourse tags) containing all information about each codes (ID, name, author, creation date).
* implement an endpoint that returns information about a single code when given the ID. 
* implement both the above

Date of completion: well, this is the last missing piece.

**Comment by tanius** [comment]
> implement both the above

I'd say it will be this option. There are both code lists and code show pages in the current interface, and both of them will get a `.json` variant now. The code list JSON page will be filter-able by author, with the query interface similar to how the annotation list JSON page is filter-able right now.

It's in the making now, so expect it to be done in 1-3 days.

**Comment by damingo** [comment]
* Codes endpoint is now accessible at https://edgeryders.eu/administration/annotator/codes.json
* Codes can be filtered by creator like this: https://edgeryders.eu/administration/annotator/codes.json?creator_id=3323
* Request info about a single code with it's ID: https://edgeryders.eu/administration/annotator/codes/13.json
