### ISSUE TITLE
Implement "annotation lists per code" in Open Ethnographer

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#114]
Right now, the [Open Ethnographer admin backend](https://edgeryders.eu/administration/annotator/codes) shows the number of annotations for which each code is used, but there is no way to list these annotations.

Proposal: Add a link to the list of annotations behind each code, so that the list of links becomes "Show | Edit | Annotations | Destroy".

**Comment by albertocottica** [comment]
> Proposal: Add a link to the list of annotations behind each code, so that the list of links becomes "Show | Edit | Annotations | Destroy".

Excellent idea!

**Comment by damingo** [comment]
Done.
