### ISSUE TITLE
Fix that Open Ethnographer annotations can be saved without entering a code

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/discourse#118]
As an effect, null values are saved in the code field. Possible solutions: 

1. Saving is forbidden until the ethnographer has entered a code.
1. If no code is entered, the quote becomes the code. 

My personal preference is for solutions 1. Reason: we want to nudge ethnographers towards a well-maintained ontology, that makes it intuitive to discover the connections between what different informants are saying in different parts of a large conversation. With solution 2, a hurried or lazy ethnographer might be tempted to just highlight the quote, and that would lead to more of a folksonomy.  

We currently have almost 700 annotations in this condition. Proposed patch for these: enact 2, via script. I do not think we have a `put`method in these APIs, right @damingo? So we need to do it via database.

**Comment by tanius** [comment]
I think it makes sense to disallow annotations without codes (solution (1)).

Right now, that's not the important part of the issue though, as you can tell the ethnographers to always assign codes to new annotations. So now we need to patch for the 700 codeless annotations … yes, in the database, via Ruby console.

**Comment by tanius** [comment]
@damingo Would you fix the 700 codeless annotations today or tomorrow in Ruby console? Change them so that they use a new Open Ethnographer code, named the same as the "quote" of the codeless annotation, and owned by the author of the codeless annotation.

**Comment by albertocottica** [comment]
I would be grateful for that. 

For documentation, I attach a file with the ids of the 697 codeless annotations. I had to zip it because GitHub does not support CSVs.
[codeless_annotations_ids.csv.zip](https://github.com/edgeryders/discourse/files/1523761/codeless_annotations_ids.csv.zip)

**Comment by damingo** [comment]
Ok, updated the annotations. Also added a validation to disallow annotations without codes - will be uploaded with the next commit.

**Comment by albertocottica** [comment]
Well done, thanks!
