### ISSUE TITLE
Rename "discourse_tag" to "tag" in the annotations API

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#120]
Currently, the `discourse_tag` GET parameter in the annotations.json API is used to return annotations which are tagged with the given Discourse tag. ("Note: The tag name needs to be passed in - not the database ID.") – [see](https://github.com/edgeryders/discourse/issues/97#issuecomment-338816804).

Afterwards, [we renamed](https://github.com/edgeryders/discourse/issues/97#issuecomment-344906088) annotator tags to "codes", so we can now simply use a `tag` GET parameter to mean a Discourse tag.

For backward compatibility, the `discourse_tag` GET parameter should still work as a synonym. Documentation should contain that it is "deprecated" though.

**Comment by albertocottica** [comment]
Looks done to me: 

https://edgeryders.eu/administration/annotator/annotations.json?tag=ethno-opencare
