### ISSUE TITLE
Allow ethnographers to merge two codes

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/discourse#122]
When merging `code1` and `code2` into `code_merged`, the `code_id` field in all annotations coded with either `code1` or `code2` is assigned the code ID of `code_merged`.  `code1` and `code2` are deleted. 

This functionality was present on Open Ethnographer for Drupal.

**Comment by tanius** [comment]
I propose this should be implemented as yet another action behind each code in the list of codes. So it would then be "Show | Edit | Merge | Destroy". Both "Merge" and "Destroy" would be shown in red, as they both are "dangerous actions" that cannot be undone.

**Comment by albertocottica** [comment]
Makes sense. I guess an auto-complete list with possible values of `code2`would do the trick. Ideally, the number of occurrences of `code2` would also be shown. Also, since it is a dangerous action, better to ask for a confirmation... but you already know that.

**Comment by albertocottica** [comment]
Hello @tanius and @damingo any news on this?

**Comment by tanius** [comment]
Daniel took up the job, I'd say expect results in the next few days (under a week).
