### ISSUE TITLE
Create a web interface to access annotations by author and by Discourse tag

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/discourse#123]
APIs allow to look at annotations, individually or in a list that can be filtered in various ways (by author, or by Discourse tag). However, this is impossible in the ~~Coding view~~ administration interface, which is what actual ethnographers use. 

The coding view should allow ethnographers to look at annotations, just as it allows to look at codes. Ideally, everything that has an API endpoint should also have a web interface.

**Comment by tanius** [comment]
Connectected issue: #114 which deals with the same thing but in the Open Ethnographer backend interface.

I don't really get how you imagine annotations to be shown in the coding view (i.e. in Discourse topics) other than the way they are shown already, as highlighted pieces of text with an overlay popup on when mousing over them?

**Comment by albertocottica** [comment]
I stand corrected, I meant the admin interface. But I also want annotations by author: "give me all my annotations", or "give me all X's annotations".

**Comment by albertocottica** [comment]
I correct my correction. Issue #114 calls a list of annotations by _ethno code_. This issue calls a list of annotations by author and _Discourse tag_.

**Comment by damingo** [comment]
Done.
