### ISSUE TITLE
Create an API endpoint for accessing the ethical consent funnel variable

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/discourse#124]
Just a dictionary: return a dictionary of users with username and the value of `edgeryders_consent`. This allows us to filter away contributions authored by people who have not given a solid consent to their work being used in research.

**Comment by damingo** [comment]
Endpoint available for authorized users at: https://edgeryders.eu/administration/annotator/users.json

**Comment by damingo** [comment]
Need to fix the field name as the correct name is 'edgeryders_consent'
