### ISSUE TITLE
Reset the "pageviews" counter after import

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#13]
The [Discourse admin dashboard ](https://discourse.edgeryders.eu/admin) contains a section listing pageviews. To make that useful, existing developer-generated pageviews should be discarded when doing the content import.

**Comment by tanius** [comment]
@damingo What about this issue? :) Either do it now, or we have to forget about it, as we don't want to delete "real" pageviews from live use.

**Comment by albertocottica** [comment]
low priority, I would say.

**Comment by tanius** [comment]
Ok then. Discarding this, not worth the effort.
