### ISSUE TITLE
Limit the search on self-branded platforms to the respective category

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#130]
To not expose users on a self-branded platform (such as biofabforum.org) to content of the main platform (such as edgeryders.eu), they should only be able to find content of their own platform via the site search.

A solution would be to always silently append ` category:276` to the search string, with the ID corresponding to the ID of the category that corresponds to the self-branded platform (`276` corresponds to "Biofabrication"). This works in all cases, even if a category filter for a Biofabforum sub-category is already specified. In such a case, all `category:` filters are AND-combined. This way, the following searched all limit the results to one of the Biofabforum sub-categories only:

* `test category:276 category:274`
* `test category:274 category:276`

**Comment by damingo** [comment]
Done.
