### ISSUE TITLE
Adapt the consent funnel mechanism to be suitable for self-branded platforms

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#131]
We should adapt the [questions of the consent funnel](https://github.com/edgeryders/discourse/blob/stable/plugins/discourse-edgeryders/assets/javascripts/discourse/templates/connectors/composer-open/consent.hbs) to not confuse users signing up via the self-branded platforms. They should be generically applicable, no longer tied to the OpenCare project. For example, question 1 still mentions "my experience with the NHS" and question 2 still mentions OpenCare.

(@albertocottica you can fix the questions by editing the `consent.hbs` file mentioned above here in Discourse. Please make a pull request so we can check the changes before committing them to `master`.)

Disabling the consent funnel for the whitelabelled categories is not a meaningful option, as it would need multiple code changes and tests. Also, we would risk to not have proper consent status for potential future EU research projects etc.. It's simply faster to adapt the questions right away.

**Comment by tanius** [comment]
A proposal is contained in commit 761dc50 (in its own branch). @albertocottica , could you please check it and agree, or make change proposals? You can see the whole file online [here](https://github.com/edgeryders/discourse/blob/761dc50/plugins/discourse-edgeryders/assets/javascripts/discourse/templates/connectors/composer-open/consent.hbs).

**Comment by albertocottica** [comment]
Yes, I would like to make minor changes. GitHub won't let me: "you must be
on a branch to make modifications to this file". What should I do?

**Comment by tanius** [comment]
@albertocottica That's the Github version of the "You are in detached HEAD mode." git problem we had.

In the left top over the file where it says "Tree: 761dc50", select "Branch: new consent questions" instead. I should've sent you a link to that version in the first place.

**Comment by albertocottica** [comment]
Closed. b661ebe

**Comment by tanius** [comment]
Changes will be applied in pull request #133.

(I changed "consent funnel" to "new author's quiz". No mere mortal will know what "consent funnel" is in their e-mail subject. That's our jargon only … .)
