### ISSUE TITLE
Fix Facebook link previews for self-branded platforms

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#132]
The screenshot below shows a (newly generated) Facebook link preview when posting the link to the homepage of the first self-branded platform based on edgeryders.eu on Facebook.

![screenshot facebooklinkpreview 2018-02-28](https://user-images.githubusercontent.com/843907/36798390-68272e30-1ca2-11e8-8b2d-61047376a3f1.png)

So the remaining problem here is that the domain is shown as `edgeryders.eu` and not `biofabforum.org` as the link posted to Facebook. This  is probably contained in some oEmbed meta information in the HTML of the page. Any quick way to solve this?

(Also Facebook shows HTML code in the preview. This is however a general Discourse bug, so also on edgeryders.eu, when posting category page links to Facebook. Does not happen with links to posts / topics, which is the normal use case. We'll ignore this issue here of course.)

**Comment by damingo** [comment]
I added `<meta property="og:url" content="https://biofabforum.org/c/biofab" />` in the template head section. If this doesn't solve it, it will take more time to fix it, as meta tags are generated by Ember.

**Comment by tanius** [comment]
Solved now according to my tests, thanks!

Sporadically, users told that they still see Edgeryders elements in Facebook link previews, but (1) it's rare and (2) we'll have to wait for a reproducible case to be able to fix this. Could still be cached previews that Facebook generated before the fix above was deployed.
