### ISSUE TITLE
Record on which platform a user signed up

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#134]
A user may now sign up on our main platform (edgeryders.eu) or a number of self-branded "whitelabeled" platforms. All are hosted in the same Discourse database, and right now there is no way to know who signed up where. This would however help when welcoming users etc..

So, this information should be recorded in a custom user profile field, and shown to moderator and admin users when viewing user profiles.

**Comment by tanius** [comment]
This issue would also be solved by re-implementing whitelabeling (#129), so if the re-implementation happens in the near to medium future (≤2018-07), the first implementation in the current context can be omitted. However, we decided 2018-03-21 that the re-implementation will not happen in the near term, so it's a go-ahead to fix it in the current codebase …

**Comment by damingo** [comment]
A "Signed up on:" attribute is now displayed in the head section of the users profile page.
The domain name is now also mentioned in the automatically created posts in this [thread](https://edgeryders.eu/t/new-members-on-edgeryders-eu/6710) about new members.
