### ISSUE TITLE
The "Browse all categories" link from biofab.org points to edgeryders.eu

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/discourse#135]
When I visualize a topic in biofab I see this:

![image](https://user-images.githubusercontent.com/1976806/37480453-922235de-287f-11e8-8fa3-fa926672dd28.png)

If I click on "Browse all categories" I see the Edgeryders categories, with the biofabforum logo: 

![image](https://user-images.githubusercontent.com/1976806/37480685-2b238ad0-2880-11e8-9d0f-7d0e57591710.png)

Notice that I do this with a non-admin user.

**Comment by damingo** [comment]
Fixed it by hiding the links. They were not supposed to be there and not needed.
