### ISSUE TITLE
Create an "orientation message" for first time users

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/discourse#14]
The switch from Drupal to Discourse will wrongfoot many users. 

I suggest creating a "welcome and orientation" message (maybe a pop-up) with friendly, reassuring content, explaining we are upgrading the platform, that login information still works, and linking to a post explaining the move. 

We also need the post, though @tanius has already written about it in admin-only spaces.

**Comment by damingo** [comment]
Luckily discourse has a build in feature for this. As admin user click on the wrench icon displayed at the upper right corner of an article page, then "Pin Topic...", then choose "Banner Topic".

**Comment by albertocottica** [comment]
Thanks @damingo . What category should I use? "Help and feedback"? Something else?

**Comment by tanius** [comment]
"Help and Feedback" is good. All our documentation will go in there.

**Comment by albertocottica** [comment]
Done: https://discourse.edgeryders.eu/t/dont-panic-breathe/6456

I do not have admin powers, so one of you guys will have to set it as banner for me.

**Comment by damingo** [comment]
Done. I also adapted the post a little as otherwise the image would have been truncated.

**Comment by tanius** [comment]
Also tweaked it a little. Looks good for "normal" users as well, so this is done :)

**Comment by albertocottica** [comment]
Broken link to the picture 

![image](https://user-images.githubusercontent.com/1976806/28108794-0a9e09c0-66ed-11e7-9951-c70a011dbb63.png)

**Comment by damingo** [comment]
Some other images are broken as well. The reason is that the hostname in the discourse config is already set to "edgeryders.eu" instead of "discourse.edgeryders.eu". So discourse is looking for the images in the wrong place, but it will work as soon as we go live with the website.

**Comment by albertocottica** [comment]
Aha. Great, thanks!
