### ISSUE TITLE
Markdown tables don't work

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/discourse#142]
In 2017 Discourse introduced [Markdown tables](https://meta.discourse.org/t/create-a-table-using-markdown-on-your-discourse-forum/66544). Do we have them? They don't seem to work for me.

**Comment by tanius** [comment]
No, we don't have them yet. As we customized Discourse, updates are not that easy, so we do them "only" when a new project starts.

But @damingo is working on updating Discourse to the latest upstream version as we speak, so expect a small truckload of new features incl. Markdown tables to become available in a few days.

**Comment by albertocottica** [comment]
Noted. Thanks!

**Comment by tanius** [comment]
As a result of our recent Discourse update, Markdown tables are possible now.

Documentation and a nice tool to generate and edit them is now [here](https://edgeryders.eu/t/6463#heading--2-17).
