### ISSUE TITLE
Broken numbered lists after the update

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/discourse#147]
The latest update removed a way to treat numbered lists in Discourse's flavor of Markdown. USed to be you could do this:

    1. First item
    * Second item
    * Third item

And it would show as 

1. First item
1. Second item
1. Third item

I used to use it a lot, because I could change from numbered to bullet point list by changing only the first element. Now this no longer works, so we now have a lot of broken lists: 

![image](https://user-images.githubusercontent.com/1976806/53986314-1c3b8d80-411e-11e9-84c5-d29174cfd568.png)

**Comment by tanius** [comment]
I know :( We don't want to fix that in Discourse core though. So the resolution for us has to be to find all posts using this now broken syntax, and edit them. Finding them can probably be done with a regex in the database.

In addition, there's another syntax change that broke some nested lists in our platform: to indent to the next list level, at least three spaces are needed now. Posts using only one or two have flat lists now.

**Comment by albertocottica** [comment]
> We don't want to fix that in Discourse core though

Of course not.

**Comment by tanius** [comment]
Fixed it in all your posts (and I think it's safe to assume only you used this Markdown syntax quirk).

For reference, the Ruby console command to find all your posts with numbered lists was:

    Post
      .where(user_id: 4)
      .where("raw ilike '%\n\n1.%'")
      .each{|post| puts "  https://edgeryders.eu/t/#{post.topic_id}/#{post.post_number}"};
