### ISSUE TITLE
What happens to incoming links?

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/discourse#15]
This is probably a stupid question, but: the web is full of links pointing to edgeryders.eu. Is there some kind of redirect table that catches them and points them to the imported content on Discourse, or are we looking at our 404 doing overtime?

This is for my welcome blog post.

**Comment by tanius** [comment]
The URL translation table you're looking for is here (from the hamburger menu):

"[Admin → Customize → Permalinks](https://discourse.edgeryders.eu/admin/customize/permalinks)"

All Drupal alias URLs for nodes and users have been imported into that table, and also the "/node/id" form of links. Direct links to comments are not imported, but those appearing inside edgeryders.eu content have been automatically changed to use the equivalent Discourse comment URLs. (External URLs pointing to individual comments are rare, we ignore these and just serve 404 …)

**Comment by albertocottica** [comment]
Great.

**Comment by albertocottica** [comment]
I don't understand how to use the URL translation table, @tanius . 

* I found this link on Google: https://edgeryders.eu/en/opencare-research/3rd-international-conference-on-internet-science. It returns 404 (and by the way: the "Google search on this site" finds again the same thing!)
* I have browsed the platform and found where it went: https://edgeryders.eu/t/3rd-international-conference-on-internet-science-caps-12th-september/5742/4

Is the image below correct?

![image](https://user-images.githubusercontent.com/1976806/28583456-7a010b74-7169-11e7-93de-58c2caa19ce8.png)

**Comment by tanius** [comment]
@albertocottica Nearly correct. In the Permalinks' "URL" field, you only have to enter the path part of the URL, so in this case: `en/opencare-research/3rd-international-conference-on-internet-science`.
