### ISSUE TITLE
Fix missing image previews when editing a post

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#150]
Currently, when editing an existing post that includes an image ([like this post](https://edgeryders.eu/t/9649/10)), images will not be shown in the editor's preview. When saving the post, the image will show up properly after saving. Also, it does not affect all images on edgeryders.eu (for example not those [in here](https://edgeryders.eu/t/6168)). Potentially only those uploaded after the recent Discourse update are affected.

We had this issue before on the Edgeryders Communities sites, where it was solved and remains  solved ([example](https://biofabforum.org/t/309)).

**Comment by damingo** [comment]
/uploads was not proxied because we had 
`<location /uploads>ProxyPass ! </location>`
which is now changed to the folder where all the actual files are:
`<location /uploads/default>ProxyPass ! </location>`
