### ISSUE TITLE
Use a codes.json?creator_id=… URL format in the Open Ethnographer backend

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#155]
Currently, the API URLs for Open Ethnographer codes are, for example with the `creator_id` filter:

```
https://edgeryders.eu/administration/annotator/codes.json?creator_id=…
```

Consequently, one would expect the backend URLs for the "Codes" tab to be:

```
https://edgeryders.eu/administration/annotator/codes?creator_id=…
```

While these URLs work, but is not the URL format used in the menu. The menu uses `/administration/annotator/codes` initially as expected, but when applying a filter it uses just `/administration?creator_id=5`. So that should be fixed please :)

**Comment by damingo** [comment]
Done
