### ISSUE TITLE
Show tags in the Annotator.js view mode in the user's preferred language

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#156]
OpenEthnographer now has code i18n: when coding, code names will appear in the auto-suggest window in the user's preferred language, if that is available, else in English, else the code's original language.

That order of language selection is not applied to the "view" mode of Annotator.js yet, though (that popover window that appears when mousing over coded text). Here, the code name will always appear in English. Even when that text has been coded immediately before, using a different language version of that code.

For example, in the current dataset, this happened with [code 3548](https://edgeryders.eu/administration/annotator/codes/3548/edit).

**Comment by damingo** [comment]
Done.
