### ISSUE TITLE
Make a single click on a row in the Open Ethnographer backend always go to view / edit mode

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#157]
When navigating in the Open Ethnographer backend to [Annotations](https://edgeryders.eu/administration/annotator/annotations), [Languages](https://edgeryders.eu/administration/annotator/languages) or [User Settings](https://edgeryders.eu/administration/annotator/user_settings), one will see a list of rows in each case.

Clicking on text in a row of such a list will navigate to a view or edit mode for that row. So far, so good.

But when clicking on a non-text area of such a row, the row will only be marked with a blue frame around it, but the page will not switch to the view / edit mode. This is confusing, as the mouse-over cursor is the same as over text (hand cursor, indicating a hyperlink). Also, the "blue frame" selection is confusing, as there is currently no way to apply any action on that selection, or to select multiple rows at once. So it seems better / more intuitive to just switch to the view / edit mode for any click on a row.

**Comment by damingo** [comment]
Disabled the on-hover behaviour as it was provided by a Gem and not easy to customize.
