### ISSUE TITLE
Write a "Where's my stuff?" text explaining categories and tags

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/discourse#16]
This stuff appeared in several places, mostly on the Matrix chat (where it's all but irretrievable). A structured version was written by @tanius here: https://edgeryders.eu/en/comment/27956#comment-27956 . It is the old platform, so the link might break after the switch. Even there it's written with the development team, not the users, as an intended audience.

**Comment by albertocottica** [comment]
@tanius do you have an initial writeup stashed somewhere, one for internal use? I can volunteer to adapt it for general consumption.

**Comment by tanius** [comment]
I think category and tag structure on our new platform have settled now, so let's document them. We even have a [user manual](https://edgeryders.eu/t/6463) now, where this content would be added in a sub-section of section 2.

Assigning this task to @anuzement :)

**Comment by tanius** [comment]
Done by @anuzement now, see the [user manual](https://edgeryders.eu/t/6463) in section "2.3. Using categories and tags".
