### ISSUE TITLE
Switch OpenEthnographer to a more adequate URL structure

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#164]
We want to make Open Ethnographer a bit of a more finished software product, perhaps packaging it as a Discourse extension for distribution in the future. For that, we'd like to have "more beautiful" and more consistent URLs, joined together using one path prefix.

Proposal of the changes:

* `/annotator_store/topic/1234` → `/openethnographer/topics/1234`
* `/annotator_store/image/1234` → `/openethnographer/images/1234`
* `/annotator_store/video/1234` → `/openethnographer/videos/1234`
* `/administration/annotator/codes` → `/openethnographer/codes`
* `/administration/annotator/codes/1234` → `/openethnographer/codes/1234`
* `/administration/annotator/annotations` → `/openethnographer/annotations`
* `/administration/annotator/languages` → `/openethnographer/languages`
* `/administration/annotator/user_settings` → `/openethnographer/user_settings`

**Comment by damingo** [comment]
URLs are now consistently namespaced by `/annotator/`. It's more generic than `/openethnographer/` and more in alignment with the name of the gem (annotator_store).

**Comment by tanius** [comment]
Thanks! The `/annotator/` URL namespace is a good choice, as it prepares the software for a possible future renaming and a role as a generic annotation / bookmarking solution for Discourse (#180).
