### ISSUE TITLE
Provide a "Topics" section in the Open Ethnographer backend

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#165]
Right now, Open Ethnographer is split into a "frontend" coding view ([example](https://edgeryders.eu/annotator_store/topic/10017)) and the "backend" for administrating codes, searching for existing annotations etc.. That's probably confusing, as there are no links to go from frontend to backend and back. Also, a strict separation between frontend and backend seems to no longer make sense as both are provided by our own Ruby on Rails views.

So let's have a new section "Topics" in the left navigation sidebar of Open Ethnographer. Let's put it between the "Codes" and "Annotations" sections because that seems the most logical: you first need to have codes before coding topics, and then you have annotations as a result.

When clicking on that "Topics" area, one would see a list of topics that have been coded already, a filter by creator to filter the list, and a sort option by newest annotation (allowing an ethnographer to quickly pick up on where they left off the coding work last time).

For each topic in this list, there would be a link to the Open Ethnographer coding view. When clicking it, the usual coding view would open, but inside (what is now called) the Open Ethnographer backend. Means, preserving the left sidebar and rendering the Discourse topic into the usual white content area of the backend.

Taken together, this integrates all parts of Open Ethnographer into a single user interface.

**Comment by tanius** [comment]
For consistency with the proposed new URL schema (see #164), we'd also have to provide sections for "Images" and "Videos".

This could be useful as one might want to see a list of coded images and videos (which are in a way "special" or "precious"). Or it could not be useful, as images and videos can only appear as parts of topics. To be decided.

**Comment by damingo** [comment]
The proposed sorting wasn't implemented as it doesn't add much value and isn't easy to implement. Can be implemented later if requested by ethnographers.
