### ISSUE TITLE
Fix that the Open Ethnographer coding view crashes when encountering external video files

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#168]
So far, I found one topic where clicking "Coding View" will lead to a crash: [this one](https://edgeryders.eu/t/open-ethnographer-tests/10246). The [coding view for that topic](https://edgeryders.eu/annotator_store/topic/10246) shows this errror message:

> **Oops**
> The software powering this discussion forum encountered an unexpected problem. We apologize for the inconvenience.
> 
> Detailed information about the error was logged, and an automatic notification generated. We'll take a look at it.
> 
> No further action is necessary. However, if the error condition persists, you can provide additional detail, including steps to reproduce the error, by posting a discussion topic in the site's feedback category.

The topic simply contains a Onebox link to an external MP4 video file:

    https://i.imgur.com/cLEzWIh.mp4

It will be embedded by Discourse just like locally uploaded video files. If possible in any way, Open Ethnographer should be usable for coding this kind of externally hosted videos. Coding externally hosted _images_ is not needed as that case does not happen. But for videos it would really help, as a way to keep our backup sizes manageable.

**Comment by tanius** [comment]
Further tests: when embedding the same video as a file uploaded to Discourse, everything works fine – see [this topic](https://edgeryders.eu/t/formatting-tests/9582).

**Comment by damingo** [comment]
Annotation of external videos is not possible.
