### ISSUE TITLE
Fix that SSO provider site mod / admin rights get synced to other Discourse sites on login

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#178]
Currently, a user's moderator and admin status on our login site communities.edgeryders.eu are synced on login to a Discourse site to which the user has access with the same account via our single-sign-on mechanism.

This means that a user can also lose mod / admin status this way: a user who has been admin on one of the Discourse sites but not on communities.edgeryders.eu will lose that status when logging out and in again on that Discourse site. To prevent that, the only workaround right now is to make everyone who needs mod / admin rights on _one_ of the Discourse sites admin on communities.edgeryders.eu, which again makes them latently moderator / admin on _all_ the Discourse sites. Which is of course not a suitable long-term fix …

There should be an "[SSO overrides](https://edgeryders.eu/admin/site_settings/category/all_results?filter=sso%20overrides) staff status"  setting for this kind of behavior that lets the SSO client site enable or disable this. It should be disabled by default and disabled for all our Discourse sites that are SSO clients.

This fix should also be contributed upstream to Discourse.

**Comment by damingo** [comment]
Done.
