### ISSUE TITLE
Do not let SSO override the avatar and profile / card backgrounds

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#179]
When deploying single-sign-on, we decided to let it sync the avatar image, user profile background and user card background from our SSO provider site to connected Discourse sites.

However, there are two problems with this:

1. Only about 10% of users set an avatar image now. It probably seems "too much work" to most switch over to another site, change the avatar there and re-login. Most users contribute mainly to one Discourse site, and might set a profile picture at least there if it is less work.

2. It is still possible to change the user profile background and user card background on edgeryders.eu (and possibly the multisite Discourse sites acting as SSO clients as well). But these changes will be overwritten on next login.

To fix this, we better (1) disable these overrides in all SSO client Discourse sites, and (2) adapt the text in the blue box at the top of the "Account" and "Profile" preferences pages that right now tells people:

> Username, name, email, profile picture, profile background and user card background can be changed on the Edgeryders Communities site.

**Comment by damingo** [comment]
Done.
