### ISSUE TITLE
Provide the Open Ethnographer creator filter as a dropdown

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#187]
The Open Ethnographer admin pages for codes, topics and annotations all have a way to filter by creator at the top. This is currently done with links, but as more ethnographers contribute now, the list becomes crowded already.

Proposal: Use a dropdown instead.

Also while we are at this, let's switch from the word "creator" to "author", both in the user interface and in the associated URL GET parameters. That is also a good preparation for the future rebranding as a general annotation solution for Discourse (see #180).

**Comment by damingo** [comment]
Dropdown filter is implemented but it's still named "creator" as there are "creator_id" columns in the DB and renaming it in the UI and controller but not renaming it in the DB creates a mess. Renaming it everywhere is to much work for the benefit.

**Comment by tanius** [comment]
Keeping the naming as "creator" is ok under these circumstances :slightly_smiling_face: 

But I'm re-opening this as the "Topics" section still uses the list of links instead of the dropdown.
