### ISSUE TITLE
Fix "Suggested topics" list so that it shows non-random, actually relevant topics

### ISSUE THREAD

**Issue by noemisalantiu** [edgeryders/discourse#19]
For users reading a topic(+comments) and scrolling down to Suggested topics, ideally the section should render other topics in the Category/ Subcategory in which the user is browsing.

**Comment by tanius** [comment]
As a workaround, let's just disable the "Suggested Topics" section until this is resolves.

**Comment by tanius** [comment]
This was actually simple to fix, as there was a Discourse admin setting "Only show topics from the current category in suggested topics." I enabled that setting, so I'm closing this issue for now. Re-open if suggestions still seem random. (All the admin settings governing this are [here](https://edgeryders.eu/admin/site_settings/category/all_results?filter=suggest) – link meant to work after our switch to Discourse.)
