### ISSUE TITLE
Run the URL rewriting script on the "About the … category" topics

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#20]
Content in the pinned "About the … category" topics in each category was not created during the initial import, but later from category descriptions (solving #18). As a result, any hyperlinks to edgeryders.eu in this content have not yet been rewritten to point to the equivalent Discourse content.

Should be fixed by running our custom URL rewriting script on these topics as well.

(Not urgent, as nearly all the old links should still work via the permalink redirects created for them inside Discourse.)

**Comment by damingo** [comment]
Done.
