### ISSUE TITLE
Create a report for monitoring coding activities with Data Explorer

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/discourse#208]
Managing research entails keeping an eye on what the ethnographers are doing across the different projects. It would be great to have a few reports in the "Admin" section of Discourse.

* Number of annotations per day per project and per author
* Count of annotations per project and per author

**Comment by tanius** [comment]
Here is the list of the requested reports – I'll add them here as I create them:

* [number of annotations per day per author](https://edgeryders.eu/admin/plugins/explorer/?id=2)

**Comment by tanius** [comment]
Your requested reports are available now using the links above.

Instead of "per project" I used "per top-level category" as the `ethno-*` Discourse tags are usually not properly applied while a project is still running.
