### ISSUE TITLE
Re-implement the OpenCare consent funnel in Discourse

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#22]
In the edgeryders.eu Drupal 7 based platform, we have a popup form that we call the "consent funnel": it asks users to answer some questions before they are able to post in certain categories (resp. in Drupal, challenges). They can only proceed past the form when they have answered its questions correctly.

**This is an "important" part of one of Edgeryders' projects**, and should be added at most a few days after going live with the Discourse platform.

@albertocottica proposed to implement it for the whole edgeryders.eu site, instead of just for certain categories. In that case, the questions would be reworded slightly from their current state. (One set of questions would be in use, site-wide.)

**UX proposal.** From the UX side, a possible way to implement this would be as, or similar to, the yellow "educational" help messages Discourse shows the first two times when a user posts a topic or reply. The messages are configured at "Admin → Customize → Text Content → education.*" in Discourse.

**Implementation proposal.** Our current Drupal 7 implementation is [module edgeryders_consent](https://github.com/edgeryders/edgeryders-commons/tree/master/sites/all/modules/edgeryders_consent), based on an open-source JavaScript library called "quizlib". This has the advantage that the whole form filling (incl. multiple trials to answer and automatic replies to that) is managed in the browser. The server only needs to finally save "timestamp when the user passed the consent funnel" into some field in the user profile. Also, since the implementation is mostly JavaScript, it should be possible to re-use the actual consent funnel form inside Discourse with little changes and effort.

**Also import the existing data.** We have to import existing "consent timestamps" because they define which user contributions we may use for Edgeryders' research projects. The existing consent funnel data is stored in Drupal's `field_data_field_consent_opencare` database table.

**Comment by tanius** [comment]
Also assigning Alberto, as he offered to help with rewording the new questions, and putting them into the source code.

**Comment by albertocottica** [comment]
Accept the assignment. From an initial check,  I think we might keep the two questions in [the quiz.html.inc file](https://github.com/edgeryders/edgeryders-commons/blob/master/sites/all/modules/edgeryders_consent/quiz.html.inc ), only rewording a bit the accompanying text in the same file.

**Comment by albertocottica** [comment]
Still not working: created [this](https://discourse.edgeryders.eu/t/test-topic/6484) without seeing the consent funnel.

**Comment by damingo** [comment]
@albertocottica: The file to reword the questions is [this](https://github.com/edgeryders/discourse/blob/master/plugins/discourse-edgeryders/assets/javascripts/discourse/templates/connectors/composer-open/consent.hbs).

**Comment by albertocottica** [comment]
Changed the wording with commit 6978db4.

**Comment by tanius** [comment]
The consent funnel is implemented now, using the same JavaScript "Quiz" component as in Drupal but integrated above the Discourse editor.

A few problems remain with this implementation, but will be handled in their own issues: importing existing consent records (once we know which ones are valid); submit button on mobile (#37); lack of a success message when answering correctly.
