### ISSUE TITLE
Provide sub-category previews on main-category pages

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#23]
As reported by John in the dev:edgeryders.eu Matrix chat:

> "In the [top-level categories view](https://edgeryders.eu/categories), you can see all the sub categories [listed].  But when you are in one of the categories that contains sub-categories, you can't see the sub-categories like that. You can only see them in a linear fashion in the [filter] list. I think that is too bad, because those lists get very long with so many […] [sub-categories]."

There is a feature in Discourse that would provide pretty exactly what we need. You can see it in the [plugin category on meta.discourse.org](https://meta.discourse.org/c/plugin), where sub-categories are shown as little cards / boxes on a main category's page.

I could not yet find how to enable this feature. Maybe it is the ["category image logo" feature](https://meta.discourse.org/t/44171) (to be tested), or maybe it is only part of the paid Discourse SaaS hosting solution.

**Comment by tanius** [comment]
Just found out how to do this (and enabled it for our category Open Care, see there). Instructions:

1. Go to the category's page (for example, [/c/opencare](https://edgeryders.eu/c/open-care)).
2. Go to "Edit → Settings" and enable "Show subcategory list above topics in this category."
3. Choose "Subcategory List Style: Boxes"

**Comment by johncoate** [comment]
I think that looks pretty good. Will be still better when we change the colour scheme to something other than tan brown.

**Comment by tanius** [comment]
Sure, go ahead @johncoate :slightly_smiling_face:. Should you need more or other category colors than we have right now, you can make yourself more under "Admin → Settings → Basic Settings → category colors" ([here](https://discourse.edgeryders.eu/admin/site_settings/category/all_results?filter=category%20colors) on the old site, [here](https://discourse.edgeryders.eu/admin/site_settings/category/all_results?filter=category%20colors) on the new).

That's technically a different issue though :laughing: So, closing this one in the meantime.
