### ISSUE TITLE
Fix the update issue with the GeoIP database

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#233]
Discourse includes a third-party GeoIP database. There is a [known issue](https://meta.discourse.org/t/137387) that prevents a Discourse deployment due to a failure to update this database. We did run into this on 2020-02-01 and as a workaround we made this setting:

```
# during precompile update maxmind database if older than N days
# set to 0 to disable
refresh_maxmind_db_during_precompile_days = 0
```

There is a [proper fix](https://github.com/discourse/discourse/commit/a8ffb69) which is [not backported](https://meta.discourse.org/t/137387/68) to the `stable` branch. Instead, it will be included into a new release "in a couple of weeks". Once that's done, what's left for us to do is:

1. Upgrade to the new release, when we get around to that.

2. Change the workaround setting back to its original value:

    ```
    refresh_maxmind_db_during_precompile_days = 2
    ```

**Comment by damingo** [comment]
Fixed.
