### ISSUE TITLE
Fix that multisite_account.json has become access protected

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#241]
Probably due to the Discourse version upgrade on communities.edgeryders.eu a few days ago, [our custom API endpoint multisite_account.json](https://edgeryders.eu/t/-/7904#heading--3-4) has become access protected.

For details, see [this analysis](https://edgeryders.eu/t/13926/8).

It should again become publicly accessible. Please [tell here](https://edgeryders.eu/t/13926) when done.

**Comment by damingo** [comment]
Fixed. A authentication callback needed to be skipped.
