### ISSUE TITLE
Fix the event plugin crash when visiting certain pages

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#244]
Since the recent update to Discourse 2.5, when visiting the `/tag/{tagname}` pages of certain tags, Discourse will crash and show an error like this:

> Oops
> 
> The software powering this discussion forum encountered an unexpected problem. We apologize for the inconvenience.
> 
> Detailed information about the error was logged, and an automatic notification generated. We'll take a look at it.

This does not happen with all tags. So far it was observed only at the following URL:

[https://edgeryders.eu/tag/ngi-summit-stories](https://edgeryders.eu/tag/ngi-summit-stories)

Notably, the equivalent URL using the Discourse "detailed search" still works:

[https://edgeryders.eu/search?expanded=true&q=tags%3Angi-summit-stories](https://edgeryders.eu/search?expanded=true&q=tags%3Angi-summit-stories)

**Comment by tanius** [comment]
While this error has been fixed on `/tag/ngi-summit-stories` by re-creating the tag page, it happens on a lot more pages and seems to be the last (?) remaining major source of errors in our Discourse log. According to the [Discourse error log](https://edgeryders.eu/logs/) the error is always reported like this:

```
NoMethodError (undefined method `join' for {}:Hash) 
    /home/discourse/production/shared/bundle/ruby/2.7.0/gems/activerecord-6.0.3.1/
    lib/active_record/relation/finder_methods.rb:342:in `raise_record_not_found_exception!'
```

The backtraces show that the error is caused by the Discourse Events plugin. This is pretty surely [discourse-events issue #75](https://github.com/paviliondev/discourse-events/issues/75). They claim it was fixed on 2020-02-03. If we already have the version where it's supposedly fixed and if the database migration doing the fix did run during our recent Discourse, please report there that this issue is not yet fixed resp. there is a regression. In that case, either manually fix the issue in the database or, if not easily possible, disable the events plugin for now.

**Comment by damingo** [comment]
Now fixed. The proposed solution in [discourse-events issue #75](https://github.com/paviliondev/discourse-events/issues/75) resolved it.
