### ISSUE TITLE
Fix that there is no menu item for user settings or logout on communities.edgeryders.eu

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#246]
This does not blocking signups or user contributions, but it does block users from changing their username, or from switching to a different user or from signing out for other reasons. Nobody complained yet, but we better fix it fast.

The issue is that since the recent Discourse update about 3 weeks ago, our CSS modifications of the Discourse template apparently block access to the user menu, and to "log out", which is now found under the user menu. On communities.edgeryders.eu, users must be able to change their e-mail address and username and to log out. So the following menu items should become visible again:

* [user icon menu] -> [user name menu] -> Preferences
* [user icon menu] -> [user name menu] -> Log Out

**Comment by damingo** [comment]
Has already been resolved or resolved itself. "Preferences" and "Log Out" are displayed in the menu on community.edgeryders.eu
