### ISSUE TITLE
Fix the sign-up button height on all our Discourse installations

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#247]
Currently, our custom "Sign Up" button pointing to communities.edgeryders.eu is too high compared to the "Log In" button next to it. That issue can be observed on any of the following sites when visiting in logged-out state:

* https://edgeryders.eu/
* https://biofabforum.org/
* https://forum.blivande.com/
* and any other Edgeryders Communities site

**Comment by damingo** [comment]
Fixed.
Note: For https://edgeryders.eu the fix will be deployed in the next days - for the other sites it is already deployed.
