### ISSUE TITLE
edgeryders summary mail contains json stuff

### ISSUE THREAD

**Issue by fwolfst** [edgeryders/discourse#248]
Not sure where to discuss this on the edgeryders discussion forum itself.
I get summary mails from edgeryders if I wasnt online for a week or so (discourse default) and it sometimes contains posts that are created to populate the minisites or other edgeryder tech.

These posts are pretty annoying, they eat up a lot of screenspace. And while I know that I can mute categories, tags and stuff I would prefer that this is done defaultish for me.

If this issue is budgeted I can look into discourse source code and try to draft a PR (I also do not know how exactly the "discourse-posts-as-datastore/api" work, maybe there is a very cheap solution).

**Comment by albertocottica** [comment]
> I get summary mails from edgeryders if I wasnt online for a week or so (discourse default) and it sometimes contains posts that are created to populate the minisites or other edgeryder tech.

This is a fair point, I had not thought about that.

**Comment by tanius** [comment]
I just changed the "default categories muted" setting in the Discourse Admin backend and included all the eight categories there that only contain content for the various websites fed by our Discourse installation. That should solve this issue for now.

People might create new categories for website content in the future and forget to add them to the muted categories. In that case, feel free to re-open. When doing the next big category cleanup, I will move all web content categories below one main category and mute _that_, which will then solve the issue permanently.

**Comment by fwolfst** [comment]
Might make sense to create a topic on the edgeryders forum explaining how/what to manually mute in case other people are annoyed by the json-content in their notification mails, too.

**Comment by tanius** [comment]
I muted the respective categories with JSON content for all existing users, using a Discourse batch operation to apply that setting to all existing user profiles. It will also be applied to new user profiles upon their creation.

But yes, it makes sense to explain to people how to mute categories, for example in case we miss categories that should be muted. I added a section about this to our Discourse manual now under "[2.8. Adjusting your e-mail notifications](https://edgeryders.eu/t/-/6463#heading--2-8)".

**Comment by fwolfst** [comment]
> I muted the respective categories with JSON content for all existing users, using a Discourse batch operation to apply that setting to all existing user profiles. It will also be applied to new user profiles upon their creation.

`Forms` is missing. At least it was included in my summary mail today (with "POPREBEL Health Event Registration Form").

**Comment by tanius** [comment]
> Forms is missing.

Thanks! Added it now, also applying that to all existing users. (I had thought it's already muted by muting its parent category, but that's apparently not how this mechanism works.)

**Comment by tanius** [comment]
For reference, I had to adjust the mechanism that prevents notifications about the web content ([details](https://edgeryders.eu/t/webkit-manual/13594#heading--1-4), [work left to do](https://github.com/edgeryders/discourse/issues/249)). But no changes will be noticeable for all existing Discourse users.
