### ISSUE TITLE
Fix that the non-SSO login and signup buttons are present in addition on some sites

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#264]
The issue affects most of our Edgeryders Communities sites, **except**:

https://edgeryders.eu/
https://biofabforum.org/
https://team2121.ro/
(and possibly 1-2 more)

It's probably an issue of a setting in the backend, since "Discourse SSO" was renamed to "Discourse Connect" in the Discourse 2.7.11 version that we upgraded to recently, and several backend settings changed their names as an effect of this.

**Comment by tanius** [comment]
Exception from the above: The [Blivande forum](https://forum.blivande.com/) currently also has its own local signup, but for this one, this should stay like that because they'd like to leave the Edgeryders SSO system. Here, the only necessary change is to remove the additional Edgeryders SSO signup button from the template.

**Comment by damingo** [comment]
Overview of deprecated settings: https://github.com/discourse/discourse/blob/42015fe8b2b42ac70d466e77e8ba57117a58d955/lib/site_settings/deprecated_settings.rb

**Comment by damingo** [comment]
Done
