### ISSUE TITLE
Non-admin users see protected (on Drupal) categories

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/discourse#36]
Like Future Makers Global Prototype. Might be just an admin issue rather than a bug.

**Comment by tanius** [comment]
This is an admin issue: the Drupal access rights status of groups was not part of the import, but defaults to "public" and had to be set to "locked" manually in Discourse where needed. We simply forgot that for a few.

Found one more category like this and set it to "locked" as well. All locked categories are in the [Team Spaces](https://edgeryders.eu/c/teams) top level category now, which seems an orderly way to separate public and non-public areas of the site.

So, closing here. (We may find one or two more categories later and lock them down when that happens.)
