### ISSUE TITLE
Consent funnel on mobile does not allow access to "Submit" button

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/discourse#37]
On mobile, the consent funnel is not scrollable. The submit button is therefore unreachable, out of the screen real estate.

Workaround is to access the browser's settings (I use Chrome mobile) and tick the "request desktop site" button. But it's likely that most people will not find it and get very frustrated. @tanius, I would say this is quite urgent.

**Comment by damingo** [comment]
Consent funnel is now scrollable on mobile.
