### ISSUE TITLE
Show a project intro text on category pages

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#39]
Proposed by Nadia (in Matrix chat): The project-intro static pages accessible from the top navbar ("[OpenCare](http://edgeryders.eu/opencare-intro)", "[OpenVillage](http://edgeryders.eu/openvillage-intro)", "[Festival](http://edgeryders.eu/openvillage-festival-intro)") should list all content from their respective categories at the bottom of the page.

We previously decided against it, as it would be redundant to the category overview pages, and because it would put too much content on one page to be useful. There may be better options than the current situation though, such as:

- a prominent link at the bottom to the category overview page
- or making each of the project menu items into a two-level menu, with a link added that points to the category overview page (this alternative needs to also work on mobile though, which is difficult as it would become a three-level menu there with our current setup)

So far, @noemisalantiu favors the "prominent link" alternative ("less messy"). So it may come down to making a nice, big, button-style design for such a link that we'll use across all project intro pages.

**Comment by tanius** [comment]
Actually listing topics below the introductory text content seems important for user engagement, as per #54. However, maybe we can limit this to 7-12 topics and provide a prominent "More" link below then, to not fill up the page beyond capacity.

**Comment by tanius** [comment]
We are currently investigating a solution that would display a user-removable banner with the introductory content at the top of a category. So not one global banner for the whole site (as we have configured now), but one per category.

Then, our three project-specific main menu items would simply lead to the respective categories, and on the first visit each of these pages would display a banner with intro content at their top. After removing the banner, it become a normal category page, i.e. the preferred workspace for users when reading about a project and contributing to it. (Seems quite elegant re. UX and avoiding redundant content and redundant navigation. I assume @ladyniasan will like this solution as well :wink: )

**Comment by Ladyniasan** [comment]
Yup. Like it :)

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by tanius** [comment]
Latest agreed implementation plan with @Ladyniasan and @damingo (correct me if I'm wrong …): to provide "one and only one" start page per project, display the full introductory content at the top of the project's category.

But not using a per-project "banner topic" as proposed before ­– implementing that is unnecessarily complex. Instead, we utilize this effect: when setting a category logo image for a category, it will be shown at the top of the category page, with a one-paragraph intro text to its left. (Currently, the [OpenCare category](https://edgeryders.eu/c/opencare) is an example of this.)

That intro text always comes from the first paragraph of the "About the … category" topic. The required change is to make it take the full "About the … category" topic content instead. At first, only the first paragraph would be shown though, with a "[Show more ▾](https://example.com/#)" link for unfolding the rest (without leaving the page, and without page reload). This will keep the page short, to provide good UX for returning visitors as well, who'll not have to scroll two pages to see what they came for.

With this setup, users will not need to see the pinned "About the … category" topics at all in topic lists, it will rather be confusing. So these would be manually set in all categories to "Unpin Topic" and "Make Unlisted" (both possible, I just tested it). This way, this "special topic" will not appear in the list at all.

**Comment by damingo** [comment]
Implemented. Wrap the expandable content with this code:
`<div>[details=Learn more]
CONTENT
[/details]</div>`
