### ISSUE TITLE
Change "Categories" to "Home" and make edgeryders.eu point to it

### ISSUE THREAD

**Issue by Ladyniasan** [edgeryders/discourse#41]
Please repoint edgeryders.eu from "latest" to "Categories" and change "Categories" to "Home" 

""for "categories " to work as home page and be renamed "home", it should be the page that edgeryders.eu points to (click on logo, get there). Earlier in the day the decision was made that edgeryders.eu point to "latest"

**Comment by tanius** [comment]
Ok, I just made "Categories" to (again) be the frontpage.

The "Categories → Home" naming transition has to be in code (no easy hack, it seems). So we'll handle that together with the other naming transitions in issue #24. (Closing it here.)

**Comment by tanius** [comment]
In addition, we have issue #29 ("Provide a better frontpage for not-logged-in users") to care for the long-term solution what should be our frontpage.
