### ISSUE TITLE
Matrix issue: Can we remove rooms?

### ISSUE THREAD

**Issue by Ladyniasan** [edgeryders/discourse#43]
We set up a number of rooms before knowing that they couldn't be closed from within the application. Could I ask that you remove all these rooms?
https://riot.im/app/#/room/!nmmbiMhOQrtbcEBigU:edgeryders.eu
https://riot.im/app/#/room/!ybKHGekLvQmnULywrU:edgeryders.eu
https://riot.im/app/#/room/!CLbzVsIYQrZftrIWyk:edgeryders.eu
https://riot.im/app/#/room/!cmxlyLjXllnXBWvWBM:edgeryders.eu
https://riot.im/app/#/room/!mvtACGRkmcLBRwmnHB:edgeryders.eu
https://riot.im/app/#/room/!uopnmNQvegJhzLXgSF:edgeryders.eu
https://riot.im/app/#/room/!tmOgYfjdyUXaQiXKvm:edgeryders.eu
https://riot.im/app/#/room/!xXTFwMDVTeYGjZFrUZ:edgeryders.eu
https://riot.im/app/#/room/!sifspQOTXzmKJUnnni:edgeryders.eu
https://riot.im/app/#/room/!xRJSklzQgKMufAlELY:edgeryders.eu
https://riot.im/app/#/room/!tjMEplXBkTpwXDqHlL:edgeryders.eu

**Comment by tanius** [comment]
I have put this on my list and will remove them with an admin script eventually.

Closing here, as this is an issue tracker only for Discourse :slightly_smiling_face: (I removed the room URLs from your report, as they are not necessarily meant to be public. Spammer danger …)
