### ISSUE TITLE
Make sure no empty passwords happened due to the migration

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#44]
One of our users (username `markomanka`) reported not being able to log in, and the reason was an empty password. Symptom: When impersonating the user as a Discourse admin, the user account settings page would contain a button "Set Password", where it would be "Send Password Reset Email" for other users.

We should make sure this issue is not a systemic issue during password migration.

**Comment by damingo** [comment]
Passwords imported from Drupal are saved in a separate table.

**Comment by tanius** [comment]
Thanks, false alarm then.

Explanation for the record: Because passwords imported from Drupal are saved in a separate table, the Discourse password field is empty until users log in for the first time and their password is re-hashed and saved to the Discourse password field.

So it's completely normal that Discourse behaves as if the user's password is unset in case of "logging in" via the "Impersonate" admin feature.
