### ISSUE TITLE
Fix that a logged in user may get stuck in the consent funnel

### ISSUE THREAD

**Issue by Ladyniasan** [edgeryders/discourse#46]
User is trying to comment (reply to topic) on this url: https://edgeryders.eu/t/notes-from-tarfaya-should-we-start-the-residency-here/6448/15

"i m trying to comment on the crew questions...very legitimate questions and i d love to participate ...wheither i answer yes or no the link (asked when i want to answer to questions within the tarfaya article)  is no clickable..."

Browser is Chrome, on a Laptop.

**Comment by tanius** [comment]
Screenshot from the incident mentioned above is attached. Not sure why the header bar is shown hovering in the center of the page. Does it simply obfuscate the second, obligatory question?

![edgeryders eu discourse issue46 screenshot censored](https://user-images.githubusercontent.com/843907/28566964-1e5b30ac-7131-11e7-85bd-672955b907f5.png)

**Comment by tanius** [comment]
Later, the same user was able to get past the consent funnel, as reported by @Ladyniasan. So, closing for now. If it re-appears, we'll need the browser version and screen resolution, please.
