### ISSUE TITLE
Users can only post one image in a post

### ISSUE THREAD

**Issue by Ladyniasan** [edgeryders/discourse#47]
Doesn't work for us.Can you remove this limitation please?

**Comment by jonathan-s** [comment]
Looks like it's already possible to upload more than one picture in a post: https://meta.discourse.org/t/css-other-customizations-setting-up-a-new-discourse-forum/52213/4

> This is already possible. Just hold Ctrl when selecting files in the upload dialog. Alternatively, drag and drop the files into the editor.

So perhaps the issue is that we need a way to clarify / make it more apparent that it is possible.

**Comment by albertocottica** [comment]
Not a bug. This limitation depends on the user [trust level](https://meta.discourse.org/t/what-do-user-trust-levels-do/4924?source_topic_id=55375). Specifically, new users can only add one pic per post. The limitation is removed as trust level goes up.

**Comment by Ladyniasan** [comment]
thanks!
