### ISSUE TITLE
Make our Agora become Discourse's Uncategorized

### ISSUE THREAD

**Issue by johncoate** [edgeryders/discourse#48]
We have already an Agoras that has been essentially a long running "uncategorized" area with a lot of existing material already in it.  Discourse insists that there be this Uncategorized category which cannot be renamed or even taken away and can not contain sub categories.  Very rigid indeed.  But for our purposes, it would be nice if our agora fulfilled that function without having to erase it or remake it manually or start all over with a new one.

**Comment by jonathan-s** [comment]
It does seem like it can be renamed though: https://meta.discourse.org/t/naming-uncategorized-category/46443

Perhaps a database migration could be made to move the Agora posts to a renamed `uncategorized`. 

Another note on categories, when you create a new post the amount of categories are overwhelming. I think some sort of house cleaning among the categories would probably be a good idea.

**Comment by tanius** [comment]
The efficienct way to implement this is bulk category re-assignment for all topics in the "Agora" category to be now in the "Uncategorized" category, and after that renaming "Uncategorized" to "Agora" (or ideally, a better name … hangout? campfire?).

These bulk-actions are available in category pages after clicking the "list icon" at the top-left corner of the actual list, and then looking for the "wrench icon" that will appear at the top right and give access to bulk actions. Make sure to scroll down a lot before to make "Select all" select enough topics. Assigning to @johncoate , hope that's ok :)

**Comment by tanius** [comment]
And thanks @jonathan-s for the comment about category selection (I agree with that). Made another issue for it [here](https://github.com/edgeryders/discourse/issues/55).

**Comment by tanius** [comment]
Actually @johncoate, let's **not** re-use the "Uncategorized" category as our "Agora" category. I just saw it has no way to change the default description, and may have other special behavior that may make us regret such a move lateron.

As a normally empty dump of not-yet-sorted content, it's actually a good thing to have. And by setting it to be suppressed from the homepage, we don't confuse people too much either.

**Comment by johncoate** [comment]
I agree...and thought the same not long after I brought it up.

**Comment by jonathan-s** [comment]
@tanius You can change the default description :) It's right here: https://github.com/edgeryders/discourse/blob/master/config/locales/server.en.yml#L486 If you search for `uncategorized` there you'll see some of the behaviour that uncategorized has, such as not being able to have a parent category.
