### ISSUE TITLE
[Feature request]: Can we haz ticket management system for official email addresses?

### ISSUE THREAD

**Issue by Ladyniasan** [edgeryders/discourse#51]
We need a system for responding to help requests, enquiries etc coming in through the edgeryders non-personal email accounts. One in which they are sent to a ticket handling app and then people can take turns to respond to tickets in batches. If they can automagically have different header tickets to reflect which email address they are coming from...

Community@edgeryders.eu
Company@edgeryders.eu
travel@edgeryders.eu
finance@edgeryders.eu
admin@edgeryders.eu
tech@edgeryders.eu

**Comment by tanius** [comment]
I have put this task into my personal list now. Installation is done at support.edgeryders.eu and will be functional in a few days.

(Closing the issue here, as this issue tracker is only for issues related to our Discourse installation, not other software / tech related tasks.)
