### ISSUE TITLE
Re-implement OpenEthnographer, to work with Discourse

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/discourse#52]
This consists of two pieces:

1. Rename the Drupal site, ex. `legacy.edgeryders.eu`
1. Write a "reverse import" script to copy new content from Discourse onto Drupal. Drupal is where ethno coding continues to happen, and where GraphRyder takes its data.

**Comment by albertocottica** [comment]
We have discarded this course of action. The relevant issue is #27.

**Comment by tanius** [comment]
_(Renaming. The goal is to enable OpenCare data analysis, the means is to re-implement OpenEthnographer. No significant changes to Graphryder are needed, since we can provide the same JSON API that it has been using from Drupal 7 and OpenEthnographer so far.)_
