### ISSUE TITLE
Text formatting missing for static pages

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/discourse#53]
https://edgeryders.eu/t/open-data-driven/37 

I manually fixed this page now: check revision history to see how it was before the fix. 

All "Company" pages appear to be this way.

**Comment by tanius** [comment]
I think this happened b/c John copied over the content originally as pure text, supposing we need to do heavy editing / rewriting / formatting anyway.

Not a bug in the import script, as all pages in the "[Menu Content](https://edgeryders.eu/c/help-feedback/menu-content)" category have been created manually.

**Comment by tanius** [comment]
Fixed. (I added the missing formatting manually. Also affected the "Netiquette" and "Terms of Use and Privacy Policy" pages in the "Community" menu.)
