### ISSUE TITLE
Is it possible to have topics belonging to a category not show up below the "About" pinned topic for the category?

### ISSUE THREAD

**Issue by Ladyniasan** [edgeryders/discourse#54]
This is a pinned topic for the OpenVillage Category: https://edgeryders.eu/t/about-the-openvillage-category/25

It is a natural place to see OpenCare topics, but they do not show up below the explanation like they do in the category page: https://edgeryders.eu/c/open-village

It looks like the category is empty, which is not great for engagement. Can we please change this so that all topics posted in a category also are visible on URL for their respective pinned topics?

**Comment by tanius** [comment]
For engagement, it seems there should be _one_ place to point new people to, and that would include a list of content in the respective category.

For that, we're working on such content lists at the bottom of our static "project intro" pages over here: ["List category content on project-intro pages" #39](https://github.com/edgeryders/discourse/issues/39). Closing in favour of that one, as treating some "normal" topics in a special way would rather hinder users from grasping the concepts of how Discourse works.
