### ISSUE TITLE
Remove excess Markdown linebreaks from HTML lists

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#63]
Currently, whenever an imported topic has HTML like this:

    <ul>
    <li>
    Some text here.</li>
    <ul>

It will be shown like this:

  * &nbsp;
  Some text here.

Since there are quite some lists like this, this should be fixed by a script, so the HTML source looks like this:

    <ul>
    <li>Some text here.</li>
    <ul>

**Comment by damingo** [comment]
Done.
