### ISSUE TITLE
Implement basic integration with PayCoupons

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#65]
@damingo and I eventually want to integrate our moneyless marketplace platform [PayCoupons](https://pay.coupons/) with the edgeryders.eu Discourse platform. (If necessary, this will be done independent of any current project budget. There's still the flexible tech budget, PayCoupons of course :laughing: or investing own time.)

**Benefits of the integration** for Edgeryders would be:

- A tool for our OpenVillage house infrastructure that allows to collect "moneyless rent" from participants, keeping up the attractive offer of being able to live in these OpenVillage houses without paying money.

- A tool for our OpenVillage house infrastructure that allows inhabitants to collaborate without money around the business founding / open source / house improvement projects. Could become a core tool for a new type of post-job / pre-market project and business incubator.

**Our current proposal**, here for discussion and feedback: we want users to be repeatedly hinted to the existence and usefulness of the PayCoupons platform, as follows:

1. For users who have a PayCoupons account, and linked to it in their Discourse profile, there would be a little badge behind their username whenever they post. Very similar to how the "moderator" badge that is shown now, but in color. When mousing over it, a tooltip overlay would say: "This user has a linked PayCoupons account."

2. In the profile preview overlay after a single click on a username or avatar, there's be the PayCoupons logo again, with a link to their PayCoupons profile and a sentence like "You can pay me without money on PayCoupons."

3. And on the user's full profile page, there would again be the PayCoupons profile link, and perhaps even a list of the offers they have on their PayCoupons profile.

4. For users who have not yet created or linked a PayCoupons account, there could be a little button on their profile preview popover and profile page saying "Want to collaborate? [Ask for PayCoupons]". Because we need to motivate people to start using PayCoupons, and getting collaboration requests from inside the Edgeryders community could be motivating enough.

All of this would be packaged as a single open source Discourse plugin, so other Discourse platforms can integrate with PayCoupons as well.

**Comment by albertocottica** [comment]
Just pitching to express support for this. Super-interesting.

**Comment by tanius** [comment]
Points 1-3 of the implementation plan have been completed by @damingo  already (yay!). Point 4 we discard for now, as it seems too pesky to be asked about PayCoupons (most users will not even want to be involved in compensated collaboration via our platform). Seems better to accustom people over time with what PayCoupons is, using these little icons etc..

Will open another feature for fine-tuning the wording and explanation of PayCoupons on our platform, and for ideas to integrate it more tightly as proposed by @ladyniasan.
