### ISSUE TITLE
Adapt CSS of our extended category "About" texts

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#66]
After implementing #39, we have the full "About the … category" topic content showing at the top of each top-level category page, with a part being hidden using a `[details=Show more] … [/details]` tag.

This is what we want, it's just that the text becoming visible after clicking "Show more" should be formatted like normal topic content. So not as large as the first paragraph, not with these weird small paragraph distances in lists etc. ([Example how it looks currently](https://edgeryders.eu/c/future-makers)).

**Comment by damingo** [comment]
Done.
