### ISSUE TITLE
Hide all summary tags from short-format category descriptions

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#68]
After implementing #39, we have the full "About the … category" topic content showing at the top of each top-level category page, with a part being hidden using a `[details=Show more] … [/details]` tag.

This  is what we want, but now the category descriptions (like on `/categories`) also show the "Show more" text, and the "hide-able detail text" following it, only limited by number of characters. Instead, we don't want to see these two things here, so the whole HTML5 summary element resulting from the `[details]` tag should be removed. Also ideally, Discourse should use its original way of creating this summary: take the first paragraph only – and then, in addition, remove HTML5 <summary> elements, if there are any.

(The current implementation will remove "Learn more", but only that text. Which is a bit too much of a hack :slightly_smiling_face: .)

**Comment by damingo** [comment]
Only the first paragraph is now used for category description excerpts.
