### ISSUE TITLE
Tags hierarchies directly implemented in Discourse core! 

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/discourse#71]
Not really an issue, just a note for when OpenEthno gets ported to the new platform. 

[Just read this](https://meta.discourse.org/t/tags-category-restrictions-tag-groups-relationships/48260/7). Using tag groups and parent tags of groups we can do quite a lot. 

Two remaining problems: API documentation does not mention `put` methods for individual tags. I hope that's just a hole in the documentation! Tag groups (hierarchies) do have a documented `put` method, but the hierarchy is a tree, not a DAG. The same tag cannot be child of two parents. However, the same tag can be included in different groups. 

In fairness, OpenEthno codes will probably be implemented separately anyway, with their own DB table.

**Comment by tanius** [comment]
Indeed we implemented Open Ethnographer for Discourse with its own database tables, not relying on Discourse tags. So I'm going to close this issue / note.

(The Discourse tag groups feature has the disadvantage that it's quite clunky to manage in the UI. We are trying right now with the `cat2-*` tags on edgeryders.eu.)
