### ISSUE TITLE
Make the "From:" name in direct message e-mails be the platform's name

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#75]
Currently, e-mails sent by Discourse when users send direct messages to each other use the user's Discourse username name together with contact@edgeryders.eu in the From: address, for example:

    From: john_doe <contact@edgeryders.eu>

This creates confusion, as recipients tend to answer by e-mail without checking the actual address the e-mail will go (some e-mail programs show it only on-hover). (As reported by @noemisalantiu.)

**Solution proposal:** Make the From: name "Edgeryders", or (maybe better) "{username} via Edgeryders", which is the format used by Facebook etc.. And, if necessary adapt the wording of the e-mail template so it's clear that it is a direct message send via the edgeryders.eu platform, and that replying by e-mail is not possible. Ideally, enable replying to direct messages by e-mail (relayed by Discourse after receiving the reply e-mail), if that is a feature provided by Discourse.

(It is not a suitable alternative to make the e-mails come from the sending user's e-mail address. Because the edgeryders.eu server is not authorized in SPF records, DKIM records etc. to send e-mail on behalf of most of the users, so they would all end up in the spam folder, or not reach their destination at all. Also, disclosing the e-mail address of the sending user would need us to add a warning on the direct message form about that.)

**Comment by damingo** [comment]
From: is now {username} via Edgeryders.

**Comment by tanius** [comment]
As a side effect, replying by e-mail now works!! :slightly_smiling_face: I just tested it successfully.

Discourse will create a reply to a direct message thread and to a normal thread when replying by e-mail to Discourse notifications, using the reply function of your e-mail software. This works because the reply-to address now has a special key embedded by which Discourse knows where to place the reply. For example, a reply-to address will look like this: `a2b56995a81e4588e81a5571e63fd68f@reply.edgeryders.eu`.
