### ISSUE TITLE
Hide the name field and custom fields from the signup form

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#77]
The "Name (your full name, optional)" field shown on the Discourse signup form should be hidden, as we do not need it and we want a minimalistic sign-up form. We don't need it because we have the convention of identifying people by @username anyway, and that people will include as much of their real name in their username as they are comfortable with. (It's ok though to keep the field in the profile settings form after signup, for those who really want to give their real name.)

Also currently, our Discourse signup form also shows the two custom fields we added to user profiles:

* Edgeryders consent (for the consent funnel form)
* PayCoupons profile

These should be hidden using CSS.

**Comment by damingo** [comment]
Fixed with CSS overwrites.
