### ISSUE TITLE
Implement e-mail notifications when new users sign up

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#78]
For community managers (and other interested regular users) to welcome new members into the community, they'd like to be notified by e-mail about new user signups to Discourse.

**Non-working options.** Out of the box, this is only possible when enabling admin approval for signups (which we don't want, and don't need, as there are only a few spam users). An alternative is to use a Discourse webhook and Zapier to transform user signup events into e-mails, but this may be buggy still ([source](https://meta.discourse.org/t/how-to-get-email-notifications-when-new-users-have-signed-up/57783/4)), and also there is no way for non-admins to self-register for receiving these e-mails.

**Current proposal.** The best idea so far seems to create a small plugin that is called when a new user signs up, and adds a comment to a configurable topic about that. Something like: "We're glad to welcome … to our community." Then, anyone who wants to be notified about these events can simply set the notification level of that thread accordingly ("Watching" to get immediate e-mail notifications, "Tracking" to only get in-site and desktop notifications). If more privacy is required for this topic, it can be placed into a protected Discourse category.

**Comment by damingo** [comment]
A post is now created automatically in [this]( https://edgeryders.eu/t/list-new-members-on-edgeryders-eu/6710) topic whenever a new user signs up. Users who want to be notified about sign ups can "watch" or "track" the topic as suggested above by @tanius .
