### ISSUE TITLE
Remove "www." from PayCoupons profile URLs

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#85]
Currently, the PayCoupons icon behind a username will point to an address like `https://www.pay.coupons/matt`, automatically generated from the PayCoupons username name entered into ones Discourse profile (here, `matt`).

Instead, the generated URL should be `https://pay.coupons/matt`, which is also the forwarding target of the currently used URL.

**Comment by damingo** [comment]
No longer needed.
