### ISSUE TITLE
Design and implement the Open Ethnographer data export interface

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#86]
This is about adding a data export feature / API to the implementation of Open Ethnographer for Discourse (managed in #27). It seems clear that we will not provide the RQDA export function available in the Drupal version, as our researchers don't use RQDA anymore for analysis (@albertocottica, can you confirm?).

However, there is this requirement for the data export interface:

> Open Ethnographer should provide the same (or a very similar) JSON API as Drupal did [via Views JSON], to export its data. This will make the Graphryder tool run without any changes needed, as it gets both the nodes / comments network and the OpenEthnographer annotations as JSON views from Drupal right now. [[source](https://github.com/edgeryders/discourse/issues/27#issuecomment-317783808)]

**Comment by albertocottica** [comment]
Confirned. Given JSON APIs, you can then find a way to export to RQDA if
needed.

**Comment by tanius** [comment]
Closing in favour of #97 (API for Open Ethnographer), as APIs are the only piece of export interface we need according to the discussion above.
