### ISSUE TITLE
Remove the comment field from Open Ethnographer annotations

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#87]
Currently, creating an annotation with "Open Ethnographer for Discourse" requires to add a comment as well (and if even one character).

To allow our researchers to tag faster, and because we don't need comments at all in annotations, this requirement should be removed. In addition, the whole field where one can add a comment should be hidden (ok to do with CSS, if there is no cleaner way prepared to do it).

**Comment by damingo** [comment]
Done. Text field hidden with CSS. Comment no longer required.
