### ISSUE TITLE
Only propose own tags when creating annotations with Open Ethnographer

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#88]
As requested by our researcher, the auto-suggestions of tags should only contain those created by the tagging user.

(Later, there might be a more sophisticated way than simply hiding others' tags. But we only need it when we need to implement collaborative tagging, and not right now. Then, for example all own tags might show up, plus those of others than a tagging user marked as "reuse". Or even forking and versioning of tags. But as said, that's not for right now.)

**Comment by damingo** [comment]
Done.

**Comment by tanius** [comment]
Actually, not done yet. There was a misunderstanding about what was to be implemented. (Which meant   that we have already "only own parent codes" when editing codes in the backend now, but not what we wanted in this issue …)
