### ISSUE TITLE
Provide per-project tracking of pageviews

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/discourse#9]
Clients want to know how many visits, pageviews etc. *their project* gets, as opposed to how much *the website as a whole* gets. This is a pain point in OpenCare: we have maybe 600 pageviews a day, but how many of those go to OpenCare-related pages? The project evaluators would like to know. 

With (group-based) Drupal Commons, this is doable by url. Urls have the form `https://edgeryders.eu/groupName/nodeTitle` , so you can use RegEx in Google Analytics to make a dashboard showing only the pageviews related to `projectName`.  We need an equivalent mechanism for Discourse.

**Comment by tanius** [comment]
This also implies setting up Google Analytics in the first place, of course.

**Comment by tanius** [comment]
Update from @damingo: Google Analytics is up and running again since 2017-07-01. Now working on the per-category tracking part. Might be implemented using "Google Tag Manager".

**Comment by damingo** [comment]
Per category tracking is now working. Go to Behaviour > Site Content > All Pages. Then select "Content Grouping: Category (Content Group)".
The Dashboard in Customisation > Dashboards > Opencare is also updated to work with the new Discourse URLs.
