### ISSUE TITLE
Make Arabic text show in larger font size

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#93]
Paragraphs in Arabic script need to be shown larger than those in Latin script, for the same level of readability. This is due to the finer details of Arabic script. (No need to show individual Arabic words embedded within Latin script paragraphs larger though. Not a good idea either, as it would mess up the line height.)

Can be implemented using CSS formatting for HTML element that results from the `[text-direction=rtl] … [/text-direction]` BBCode tag.

**Comment by damingo** [comment]
Done.
