### ISSUE TITLE
Fix that same-name Open Ethnographer tags do not appear in the "Any Creator" list

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#98]
The default view of the Open Ethnographer administration interface is "[Tags → Any Creator](https://edgeryders.eu/administration/annotator/tags)". This one does not list tags of the same name (and with the same parent tag) which were created by different creators. It should, however.

When filtering by a specific creator, the corresponding tags _do_ get listed. Means, tags with the same name and different authors can co-exist (and they can be created just fine).

**Comment by damingo** [comment]
Done.
