### ISSUE TITLE
Provide an icon to switch to the Open Ethnographer view of a topic

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse#99]
Currently, one has to append `?oe=true` to the URL of a topic to go to the view for creating Open Ethnographer annotations (works, provided one is a moderator or admin).

To make this more comfortable, we'd want an icon with a link for this switching, or if not easily possible, an equivalent navigational link. When in the Open Ethnographer view (i.e. on a `…?oe=true` page), there should be the same icon / link to switch back to the "normal" view of the topic.

Ideally, to be implemented without changes to Discourse core code. So for example, by forking and adapting an existing, related Discourse plugin.

**Comment by tanius** [comment]
@damingo Could this be implemented until approx. mid October 2017? We don't have a hard deadline (as this does not add essential functionality), but we would like to provide our ethnographic researchers a nicer user experience :slightly_smiling_face:

**Comment by damingo** [comment]
Done.
